---
apiVersion: v1
kind: Secret
metadata:
  name: ordersxv3-app-repo
  namespace: devhub
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/devhub-mad/ordersxv3-app-gitops
